"use client";

import { CssBaseline, ThemeProvider } from "@mui/material";
import "./globals.css";
import { Inter } from "next/font/google";
import MainLayout from "@/layout";
import { store } from "../store/index";
import { Provider } from "react-redux";
import { theme } from "@/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <MainLayout>{children}</MainLayout>
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
